type FarmDocumentRow = { abbreviation: string; name: string };

export const farmDocumentRows: FarmDocumentRow[] = [
  { abbreviation: 'CONTRATO', name: 'CONTRATO DE COMPRA E VENDA DO IMÓVEL E/OU ARRENDAMENTO' },
  { abbreviation: '', name: 'ADITIVOS / ALTERAÇÃO E CONSOLIDAÇÃO CONTRATUAL' },
  { abbreviation: '', name: 'CERTIDÃO SIMPLIFICADA DA CONSOLIDAÇÃO CONTRATUAL' },
  { abbreviation: '', name: 'CONTRATO DE COMODATO' },
  { abbreviation: 'ESCRITURA', name: 'ESCRITURA DO IMÓVEL RURAL' },
  { abbreviation: 'MATRICULA', name: 'MATRICULA DO IMÓVEL RURAL' },
  { abbreviation: 'CCIR', name: 'CERTIFICADO DE CADASTRO DE IMÓVEL RURAL' },
  { abbreviation: '', name: 'BOLETO E/OU COMPROVANTE DE PAGAMENTO' },
  { abbreviation: 'ITR', name: 'IMPOSTO TERRITORIAL RURAL - DECLARAÇÃO' },
  { abbreviation: '', name: 'RECIBO DE DECLARAÇÃO' },
  { abbreviation: 'MAPA', name: 'MAPA DO IMÓVEL' },
  { abbreviation: 'KML / KMZ', name: 'KML / KMZ' },
  { abbreviation: 'CROQUI', name: 'CROQUI DE ACESSO' },
  { abbreviation: 'CAR', name: '(CAR) CADASTRO AMBIENTAL RURAL' },
  { abbreviation: 'ADA', name: 'ATO DECLARATORIO AMBIENTAL' },
  { abbreviation: 'GEO', name: 'GEORREFERENCIAMENTO' },
  { abbreviation: 'CEFIR', name: 'CERTIFICADO DE INSCRIÇÃO NO CADASTRO ESTADUAL FLORESTAL DE IMOVEIS RURAIS' },
  { abbreviation: '', name: 'SEIA - LOGIN E SENHA DE ACESSO' },
  { abbreviation: 'ASV', name: 'AUTORIZAÇÃO DE SUPRESSÃO DE VEGETAÇÃO' },
  { abbreviation: 'CERTIDÃO', name: 'CERTIDÃO DE CONFORMIDADE AMBIENTAL' },
  { abbreviation: 'APE', name: 'AUTORIZAÇÃO POR PROCEDIMENTO ESPECIAL DE LICENCIAMENTO' },
  { abbreviation: 'LA', name: 'LICENÇA AMBIENTAL' },
  { abbreviation: 'LP', name: 'LICENÇA PRÉVIA' },
  { abbreviation: 'LI', name: 'LICENÇA DE INSTALAÇÃO' },
  { abbreviation: 'LO', name: 'LICENÇA DE OPERAÇÃO' },
  { abbreviation: 'LS', name: 'LICENÇA SIMPLIFICADA' },
  { abbreviation: 'APPO', name: 'AUTORIZAÇÃO PARA PERFURAÇÃO DE POÇOS' },
  { abbreviation: '', name: "MAPA DAS APPO'S" },
  { abbreviation: 'OUTORGA', name: 'OUTORGA (DIREITO DE USO DOS RECURSOS HIDRICOS)' },
  { abbreviation: '', name: 'MAPA DA OUTORGA' },
  { abbreviation: 'DISPENSA OUTORGA', name: 'DECLARAÇÃO DE DISPENSA DE OUTORGA' },
  { abbreviation: '', name: 'REQUERIMENTO DISPENSA DE OUTORGA' },
  { abbreviation: 'LAUDO', name: 'ANALISE DE ÁGUA' },
  { abbreviation: '', name: 'VISITA TECNICA' },
  { abbreviation: '', name: 'LAUDO DE AVALIAÇÃO' },
  { abbreviation: 'PROJETO', name: 'PROJETO DE REFLORESTAMENTO' },
  { abbreviation: 'ARL', name: 'ÁREA DE RESERVA LEGAL' },
  { abbreviation: '', name: 'MEMORIAL DESCRITIVO DA RESERVA LEGAL' },
  { abbreviation: 'RAF', name: 'REGISTRO DE ATIVIDADES FLORESTAIS' },
  { abbreviation: 'DOF', name: 'DOCUMENTO DE ORIGEM FLORESTAL' },
  { abbreviation: 'RCFP', name: 'REGISTRO DE CORTE PARA FLORESTA PLANTADA' },
  { abbreviation: '', name: 'COMPROVANTE DE REGISTRO DE CORTE PARA FLORESTA PLANTADA' },
  { abbreviation: 'CTF', name: 'CADASTRO TÉCNICO FEDERAL' },
  { abbreviation: 'RAPP', name: 'RELATORIO ANUAL DE ATIVIDADES POTENCIALMENTE POLUIDORES' },
  { abbreviation: 'DQC', name: 'DECLARAÇÃO DE QUEIMA CONTROLADA' },
  { abbreviation: 'DIAP', name: 'DIVISÃO DE ÁREAS PROTEGIDAS' },
  { abbreviation: 'CEAPD', name: 'CADASTRO ESTADUAL DE ATIVIDADES POTENCIALMENTE DEGRADANTES' },
  { abbreviation: 'CADASTRO', name: 'FICHA ABERTURA DE CADASTRO' },
  { abbreviation: '', name: 'FICHA SANITÁRIA' },
  { abbreviation: '', name: 'LISTA DA DOCUMENTAÇÃO NECESSARIA PARA ABERTURA' },
  { abbreviation: 'GTA', name: 'GUIA DE TRANSITO ANIMAL' },
  { abbreviation: '', name: 'DAE / FUNDAP' },
  { abbreviation: '', name: 'MODELO SOLICITAÇÃO CANCELAMENTO GTA' },
  { abbreviation: 'NFE', name: 'NOTA FISCAL ELETRONICA DE VENDA' },
  { abbreviation: '', name: 'COMPROVANTES DE PAGAMENTO' },
  { abbreviation: 'PROCURAÇÃO', name: 'PROCURAÇÃO - OUTORGADO NILVA' },
];
